### ISSUE TITLE
Watching status - ToS issue

### ISSUE THREAD

**Issue by ks00908** [timmyrs/Set-Discord-Activity#1]
Hey so i noticed your addon adds possibility to generate watching status. This status is curently not allowed for user account, only bots. using it on user account is considered selfbotting which is against ToS/Api ToS.
just letting you know since id hate to see something happen to this :)

**Comment by timmyrs** [comment]
I don't see anything permitting this in the terms of service.

**Comment by ks00908** [comment]
https://hero.is-a-good-waifu.com/6XwJmdy.png watching status is also generally considered as under selfbot because 
1. no representation in client
2. no legitimate (aka official) way to generate it

**Comment by timmyrs** [comment]
A tweet is not a legal document that the user agreed to upon sign up.

**Comment by ks00908** [comment]
please read tweet in regards of selfbot
As discord tweeter stated its part of ToS, you can find similar information on discord support page ( https://support.discordapp.com/hc/en-us/articles/115002192352-Automated-user-accounts-self-bots- )
Watching status is curently treated as selfbot automatically unless used by bot account

**Comment by timmyrs** [comment]
I haven't seen anyone get banned over it. Besides, upholding Discord ToS is the responsibility of the user, after all, they agreed to them.
